import type { Metadata } from "next";

import "../styles/v2.css";

/**
 * Index of the sep-2026 rebrand previews.
 *
 * The pages themselves are static Claude Design exports served from
 * public/v2/<slug>/index.html (generated by `npm run sync:v2`), so they can't
 * link themselves into the app. This page is the way in.
 *
 * Internal only — noindex here and in robots.ts, until the rebrand ships.
 */
export const metadata: Metadata = {
  title: "v2 previews",
  description: "Internal index of the sep-2026 rebrand design previews.",
  robots: { index: false, follow: false },
};

type Preview = {
  slug: string;
  name: string;
  headline: string;
  source: string;
  note?: string;
};

const PREVIEWS: Preview[] = [
  {
    slug: "homepage",
    name: "Homepage",
    headline: "The Risk Network for AI",
    source: "Homepage/Homepage.dc.html",
  },
  {
    slug: "control",
    name: "Control",
    headline: "Control what AI can do.",
    source: "Control Risk/Control.dc.html",
  },
  {
    slug: "risk-intelligence",
    name: "Risk Intelligence",
    headline: "Get the risk answers you need.",
    source: "Control Risk/Risk Intelligence.dc.html",
  },
  {
    slug: "prove",
    name: "Prove Your AI",
    headline: "Don't just say your AI is safe. Prove it.",
    source: "Prove Risk/Prove Your AI.dc.html",
  },
  {
    slug: "pricing",
    name: "Pricing",
    headline: "Manage AI risk for free.",
    source: "Pricing/Pricing.dc.html",
  },
];

const MONITOR: Preview[] = [
  {
    slug: "monitor",
    name: "Monitor",
    headline: "Know your AI risk.",
    source: "Control Risk/Monitor.dc.html",
    note: "monitor · act · developers · pricing",
  },
  {
    slug: "monitor-v2",
    name: "Monitor v2",
    headline: "Know your AI risk. Prove it.",
    source: "Control Risk/Monitor v2.dc.html",
    note: "monitor · prove · next · developers · pricing",
  },
  {
    slug: "monitor-v3",
    name: "Monitor v3",
    headline: "Know your AI risk. Prove it.",
    source: "Control Risk/Monitor v3.dc.html",
    note: "monitor · network · developers",
  },
];

function Row({ slug, name, headline, source, note }: Preview) {
  return (
    <li className="v2-row">
      <a className="v2-link" href={`/v2/${slug}`}>
        <span className="v2-name">{name}</span>
        <span className="v2-headline">{headline}</span>
      </a>
      <span className="v2-meta">
        <code>/v2/{slug}</code>
        <span className="v2-source">{source}</span>
        {note ? <span className="v2-note">{note}</span> : null}
      </span>
    </li>
  );
}

export default function V2Index() {
  return (
    <main className="v2-index">
      <header className="v2-header">
        <p className="v2-eyebrow">Internal preview</p>
        <h1>sep-2026 rebrand</h1>
        <p className="v2-lede">
          Static Claude Design exports, served as-is from <code>public/v2/</code>. Source of truth
          is <code>sep-2026/</code>; regenerate with <code>npm run sync:v2</code>. Not indexed, not
          linked from the live site.
        </p>
      </header>

      <h2 className="v2-h2">Pages</h2>
      <ul className="v2-list">
        {PREVIEWS.map((p) => (
          <Row key={p.slug} {...p} />
        ))}
      </ul>

      <h2 className="v2-h2">
        Monitor <span className="v2-h2-note">— three versions, none picked yet</span>
      </h2>
      <ul className="v2-list">
        {MONITOR.map((p) => (
          <Row key={p.slug} {...p} />
        ))}
      </ul>

      <p className="v2-footnote">
        No design exists yet for <code>/trust</code> or <code>/use-cases</code>. Company and Case
        Studies are copy-only rewrites — see <code>sep-2026/Company.txt</code> and{" "}
        <code>sep-2026/Case Studies.txt</code>.
      </p>
    </main>
  );
}
